### PR TITLE
Join Events Done, Outing number is not correct along with the list of participants in  the event.

### PR DESCRIPTION
**Pull request by NeelSalvi**
#202

### CODE REVIEW

**Comment by PujaVerma-06** [comment]
Found the following issues while testing the application
Issue No 1:- Location permission - Didn't ask me location permission for Near You tab. It asked me location permission when I clicked on another tab after clicking on Near You tab.

**Comment by PujaVerma-06** [comment]
Issue No 2:- Trails details text out of bounds - Few trails details text overlap with other text or symbol.

**Comment by PujaVerma-06** [comment]
Issue No 3:- User DOB displays current date - While signing up, entered DOB and in the app profile page, DOB displays the current date.

**Comment by PujaVerma-06** [comment]
Issue No 4:- COVID toggle - When COVID toggle is off and a trail is clicked it gives error "Text strings must be rendered within a <Text> component".

**Comment by PujaVerma-06** [comment]
Issue No 5:- Number of outings not being displayed correctly.

**Comment by PujaVerma-06** [comment]
Issue No 6:- Data in Best Rated tab and Easy Trail tab are interchanged.

**Comment by NeelSalvi** [comment]
> Found the following issues while testing the application
> Issue No 1:- Location permission - Didn't ask me location permission for Near You tab. It asked me location permission when I clicked on another tab after clicking on Near You tab.

Should be fixed now

> Issue No 4:- COVID toggle - When COVID toggle is off and a trail is clicked it gives error "Text strings must be rendered within a component".

Fixed

> Issue No 5:- Number of outings not being displayed correctly.

Fixed by Vini (Server-side issue)

> Issue No 6:- Data in Best Rated tab and Easy Trail tab are interchanged.

Should work fine now

**Comment by NeelSalvi** [comment]
> Issue No 2:- Trails details text out of bounds - Few trails details text overlap with other text or symbol.

Need multiple devices to check this. Might change depending on the screen size.



> Issue No 3:- User DOB displays current date - While signing up, entered DOB and in the app profile page, DOB displays the current date.

@D18130435 Need to check

**Pull request merged**
